// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TDDP_BindPicturesToMap","status":true,"description":"1.0.7 Plugin Commands for binding pictures to the map and/or changing what layer they're drawn on.","parameters":{}},
{"name":"YEP_RegionRestrictions","status":true,"description":"v1.03 Use regions to block out Events and/or the player from\r\nbeing able to venture into those spots.","parameters":{"Player Restrict":"10","Event Restrict":"11","All Restrict":"12","Player Allow":"13","Event Allow":"14","All Allow":"15"}}
];
